apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.global.namespace }}
data:
  ZOOKEEPER_CLIENT_PORT: "{{ .Values.zookeeper.port }}"
  ZOOKEEPER_TICK_TIME: "{{ .Values.config.tickTime }}"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:{{ .Values.zookeeper.port }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.config.offsetsTopicReplicationFactor }}"