apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tuning-dev
  namespace: argocd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  description: Project tuning for DEV environment
  sourceRepos:
    - "*"
  destinations:
    - namespace: hertz-tuning-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
