apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: springboot-fcm-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: springboot-fcm-secret
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: tuning-fcm-certification.json
      remoteRef:
        key: "{{ .Values.externalSecrets.secretStore.path.springboot }}/TUNING_FCM"

