apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: springboot-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: springboot-secrets
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  dataFrom:
    - find:
        path: {{ .Values.externalSecrets.secretStore.path.springboot }}
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "{{ .Values.externalSecrets.secretStore.path.springboot }}/(.*)"
            target: "$1"