apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: general-workload
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.xlarge", "t3.large", "t3.medium", "t3.small", "t3.micro"] # 일반 애플리케이션 용도
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"] # On-Demand 인스턴스 사용
  providerRef:
    name: default
  limits:
    resources:
      cpu: "16" # 총 8 vCPU 이상 노드 생성하지 않도록 제한 (선택적)
  labels:
    workload-type: "general"
  consolidation:
    enabled: true