# Stage Environment Settings
global:
  namespace: hertz-tuning-stage
  region: ap-northeast-2
  accountId: "969400486509"
  environment: stage

image:
  repository: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-springboot
  tag: k8s-develop-latest

serviceAccount:
  ecrAccess: ecr-access-sa

app:
  environment: stage
  name: springboot-be
  ports:
    http: 8080
    websocket: 9100

healthCheck:
  readiness:
    initialDelaySeconds: 100
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  liveness:
    initialDelaySeconds: 150
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

resources:
  requests:
    cpu: 750m
    memory: 1536Mi
  limits:
    cpu: 1500m
    memory: 3072Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80
  scaleUp:
    stabilizationWindowSeconds: 60
    percent: 100
    periodSeconds: 15
  scaleDown:
    stabilizationWindowSeconds: 300
    percent: 10
    periodSeconds: 60

observability:
  signoz:
    endpoint: "http://cloud.hertz-tuning.com:4317"