apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.app.port }}
    - name: metrics
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}