# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: signoz
#   namespace: argocd
#   annotations:
#     "helm.sh/hook": post-install,post-upgrade
#     "helm.sh/hook-weight": "0"
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: tuning-stage
#   source:
#     repoURL: https://github.com/100-hours-a-week/2-hertz-cloud.git
#    targetRevision: {{ .Values.applications.git.branches.stage }}
#     path: k8s-argocd-helm/apps/signoz
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: observability
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true