# springboot-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-be
  namespace: hertz-tuning-dev
spec:
  selector:
    matchLabels:
      app: springboot-be
  template:
    metadata:
      labels:
        app: springboot-be
    spec:
      serviceAccountName: ecr-access-sa # IRSA Service Account 사용
      containers:
        - name: springboot-be
          image: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-springboot:k8s-develop-latest
          envFrom:
            - secretRef:
                name: springboot-secrets
          env:
            # SigNoz OpenTelemetry 설정
            - name: OTEL_SERVICE_NAME
              value: "springboot-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.observability.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=springboot-service,service.version=1.0.0,deployment.environment=dev"
          ports:
            - containerPort: 8080
            - containerPort: 9100 # 웹소켓 포트 추가
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-be-svc # 서비스 이름도 통일
  namespace: hertz-tuning-dev
spec:
  type: ClusterIP
  selector:
    app: springboot-be
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: websocket
      port: 9100
      targetPort: 9100
