# Global settings
global:
  namespace: hertz-tuning-stage
  region: ap-northeast-2
  environment: stage

# Kafka settings
kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "7.6.0"
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  storage:
    storageClass: mysql-ebs-stage
    size: 10Gi

# ZooKeeper settings
zookeeper:
  image:
    repository: confluentinc/cp-zookeeper
    tag: "7.6.0"
  port: 2181
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Configuration
config:
  tickTime: 2000
  offsetsTopicReplicationFactor: 3
