# Global settings
global:
  namespace: hertz-tuning-dev

# External Secrets settings
externalSecrets:
  secretStore:
    name: aws-ssm-store
    region: ap-northeast-2
    path: /global/k8s/springboot/dev