# Global settings shared across all charts
global:
  namespace: hertz-tuning-dev
  region: ap-northeast-2
  accountId: "969400486509"
  environment: dev

# Apps enablement
apps:
  backend:
    enabled: true
  frontend:
    enabled: true
  mysql:
    enabled: true
  kafka:
    enabled: true
  redis:
    enabled: true
  signoz:
    enabled: true

# Infrastructure enablement
infrastructure:
  alb:
    enabled: true
  network:
    enabled: true
  secrets:
    enabled: true
  reloader:
    enabled: true

# Backend chart values
backend:
  global:
    namespace: hertz-tuning-dev
    region: ap-northeast-2
    accountId: "969400486509"
    environment: dev
  image:
    repository: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com
    name: tuning-springboot
    tag: k8s-develop-latest
  serviceAccount:
    ecrAccess: ecr-access-sa
  app:
    name: springboot-be
    ports:
      http: 8080
      websocket: 9100
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 10
      periodSeconds: 60
  observability:
    signoz:
      endpoint: "http://signoz-otel-collector.observability.svc.cluster.local:4318"

# Frontend chart values
frontend:
  global:
    namespace: hertz-tuning-dev
    region: ap-northeast-2
    accountId: "969400486509"
    environment: dev
  image:
    repository: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com
    name: tuning-nextjs
    tag: k8s-develop-latest
  serviceAccount:
    ecrAccess: ecr-access-sa
  app:
    name: nextjs-fe
    port: 3000
  resources:
    requests:
      cpu: 300m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 60
    targetMemory: 70
    scaleUp:
      stabilizationWindowSeconds: 30
      percent: 100
      periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 180
      percent: 20
      periodSeconds: 60
  observability:
    signoz:
      endpoint: "http://signoz-otel-collector.observability.svc.cluster.local:4318"

# SigNoz chart values
signoz:
  global:
    namespace: hertz-tuning-dev
    environment: dev
  signoz:
    namespace: observability
    storageClass: mysql-ebs
    clickhouse:
      storage:
        size: 12Gi
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
    zookeeper:
      storage:
        size: 6Gi
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1000m"
    kafka:
      storage:
        size: 6Gi

# ALB chart values
alb:
  global:
    namespace: hertz-tuning-dev
  ingress:
    className: alb
    certificateArn: arn:aws:acm:ap-northeast-2:969400486509:certificate/0923e90f-18b8-4f6c-b33f-878e9d00cfbf
  services:
    backend: springboot-be-svc
    frontend: nextjs-fe-svc
    websocketPort: 9100

# Network chart values
network:
  global:
    namespace: hertz-tuning-dev
  apps:
    backend: springboot-be
    mysql: mysql
    redis: redis
  ports:
    mysql: 3306
    redis: 6379

# Secrets chart values
secrets:
  global:
    namespace: hertz-tuning-dev
  externalSecrets:
    secretStore:
      name: aws-ssm-store
      region: ap-northeast-2
      path: /global/k8s/springboot/dev