apiVersion: v2
name: argocd
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 8.1.2
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-image-updater
    version: 0.9.1
    repository: https://argoproj.github.io/argo-helm
    condition: argocd-image-updater.enabled