{{- if .Values.environments.prod.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-prod
  namespace: argocd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: tuning-prod
  source:
    repoURL: https://github.com/100-hours-a-week/2-hertz-cloud.git
    targetRevision: {{ .Values.applications.git.branches.prod }}
    path: k8s-argocd-helm/apps/mysql
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hertz-tuning-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}