apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: hertz-tuning-dev
spec:
  selector:
    app: kafka1
  ports:
    - name: external
      port: 9092
      targetPort: 9092
    - name: internal
      port: 29092
      targetPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  namespace: hertz-tuning-dev
spec:
  selector:
    app: kafka2
  ports:
    - name: external
      port: 9093
      targetPort: 9093
    - name: internal
      port: 29093
      targetPort: 29093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  namespace: hertz-tuning-dev
spec:
  selector:
    app: kafka3
  ports:
    - name: external
      port: 9094
      targetPort: 9094
    - name: internal
      port: 29094
      targetPort: 29094
