apiVersion: v2
name: frontend
description: Next.js Frontend Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - frontend
  - react
maintainers:
  - name: hertz-team