apiVersion: v2
name: monitoring
description: Monitoring Stack with Prometheus, Grafana, Loki
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
maintainers:
  - name: hertz-team