apiVersion: v1
kind: Service
metadata:
  name: springboot-be-svc # 서비스 이름도 통일
  namespace: hertz-tuning-dev
spec:
  type: ClusterIP
  selector:
    app: springboot-be
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: websocket
      port: 9100
      targetPort: 9100
