{{- if .Values.environments.stage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tuning-stage
  namespace: argocd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Project tuning for STAGE environment
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end }}
